version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: server
    working_dir: /home
    ports:
      - "5022:5000"
    volumes:
      - ./:/home/cookies_pool
    environment:
      - PROXY_POOL_ADDRESS=http://124.220.177.240:8425/random
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=polkjhguDNJHD2
    networks:
      - back-tier
    restart: always

  redis:
    hostname: redis
    image: redis:6.2
    networks:
      - back-tier
    environment:
      - REDIS_PASSWORD=polkjhguDNJHD2
    command: [ 'redis-server', '--requirepass', '"$REDIS_PASSWORD"' ]
    volumes:
      - redis_storage:/data/redis-data
    restart: always

volumes:
  redis_storage:


networks:
  back-tier: { }